FROM python

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app-backend

RUN pip install --upgrade pip

COPY ./requirements.txt /app-backend/

RUN pip install -r requirements.txt

COPY . /app-backend/

EXPOSE 8000

CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]